Repository AY2021S1-CS2113T-W12-2/tp, pull requests merged in 2020-10, with the labels that each got.

#12 Add skeleton code for UI, with general methods
  docs/AboutUs.md
  src/main/java/athena/Athena.java
  src/main/java/athena/Ui.java
Labels: enhancement

#11 Add tasklist and task class, with importance enum
  src/main/java/athena/Importance.java
  src/main/java/athena/Task.java
  src/main/java/athena/TaskList.java
Labels: enhancement

#10 Skeleton Code for Commands and Parser
  src/main/java/athena/AddCommand.java
  src/main/java/athena/Command.java
  src/main/java/athena/DeleteCommand.java
  src/main/java/athena/DoneCommand.java
  src/main/java/athena/EditCommand.java
  src/main/java/athena/ExitCommand.java
  src/main/java/athena/HelpCommand.java
  src/main/java/athena/ListCommand.java
  src/main/java/athena/Parser.java
Labels: documentation, enhancement

#33 Update DeleteCommand, Task and UI
  src/main/java/athena/Athena.java
  src/main/java/athena/Parser.java
  src/main/java/athena/Task.java
  src/main/java/athena/Ui.java
Labels: type.Epic

#57 Added the forecast parameter to list
  src/main/java/athena/Parser.java
  src/main/java/athena/commands/ListCommand.java
Labels: aspect.Feature, priority.High, type.Task

#43 Generate Timetable from TaskList and TaskFilter
  save.csv
  src/main/java/athena/Athena.java
  src/main/java/athena/Parser.java
  src/main/java/athena/Storage.java
  src/main/java/athena/Task.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/Ui.java
  src/main/java/athena/commands/AddCommand.java
  src/main/java/athena/commands/DeleteCommand.java
  src/main/java/athena/commands/DoneCommand.java
  src/main/java/athena/commands/EditCommand.java
  src/main/java/athena/commands/ListCommand.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/taskfilter/ImportanceFilter.java
  src/main/java/athena/task/taskfilter/TaskFilter.java
  src/main/java/athena/tasklist/TaskList.java
  src/main/java/athena/timetable/Timetable.java
  src/main/java/athena/timetable/TimetableDay.java
  src/test/java/athena/TestSetup.java
  src/test/java/athena/timetable/TimetableTest.java
  src/test/java/seedu/duke/DukeTest.java
Labels: aspect.Feature, severity.High, type.Task

#46 Prints help when unknown command is input
  src/main/java/athena/Parser.java
  src/main/java/athena/Ui.java
  src/main/java/athena/commands/DoneCommand.java
  src/main/java/athena/commands/EditCommand.java
Labels: aspect.CodeQuality, type.Enhancement

#60 Use forecast to display list
  src/main/java/athena/Forecast.java
  src/main/java/athena/Importance.java
  src/main/java/athena/Parser.java
  src/main/java/athena/commands/ListCommand.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/taskfilter/ForecastFilter.java
  src/main/java/athena/task/taskfilter/ImportanceFilter.java
  src/main/java/athena/timetable/Timetable.java
  src/test/java/athena/taskfilter/ForecastFilterTest.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.Feature, priority.High, type.Task

#66 Solve Issue #65
  src/main/java/athena/Recurrence.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/timetable/Timetable.java
Labels: priority.High, severity.High, type.Bug

#64 Junit test code for parser
  src/main/java/athena/Parser.java
  src/main/java/athena/commands/AddCommand.java
  src/main/java/athena/commands/DeleteCommand.java
  src/main/java/athena/commands/DoneCommand.java
  src/main/java/athena/commands/EditCommand.java
  src/main/java/athena/commands/ListCommand.java
  src/test/java/athena/ParserTest.java
Labels: aspect.Testing, priority.High, type.Task

#74 Test tasklist edit
  src/main/java/athena/Athena.java
  src/main/java/athena/Parser.java
  src/main/java/athena/task/Task.java
  src/test/java/athena/ParserTest.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: priority.High, severity.Medium, type.Bug, type.Enhancement

#61 Fix task number
  .gitignore
  save.csv
  src/main/java/athena/Athena.java
  src/main/java/athena/Storage.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/Ui.java
  src/main/java/athena/commands/Command.java
  src/main/java/athena/commands/DeleteCommand.java
  src/main/java/athena/commands/DoneCommand.java
  src/main/java/athena/commands/EditCommand.java
  src/main/java/athena/commands/ListCommand.java
  src/main/java/athena/exceptions/AddException.java
  src/main/java/athena/exceptions/CommandException.java
  src/main/java/athena/exceptions/TaskNotFoundException.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/timetable/TimetableDay.java
  src/test/java/athena/TestSetup.java
  src/test/java/athena/commands/DeleteCommandTest.java
  src/test/java/athena/commands/DoneCommandTest.java
  src/test/java/athena/commands/EditCommandTest.java
  src/test/java/athena/taskfilter/ForecastFilterTest.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: aspect.Feature, priority.High, severity.High, type.Bug

#78 Add assert in task
  src/main/java/athena/task/Task.java
  src/test/java/athena/taskfilter/ForecastFilterTest.java
Labels: priority.Medium, severity.VeryLow, type.Task

#62 Add basic Storage testing
  .gitignore
  save.csv
  src/main/java/athena/TaskList.java
  src/test/java/athena/StorageTest.java
  src/test/java/athena/StorageTestAnswer1.csv
  src/test/java/athena/TestSetup.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.Testing, priority.High

#63 ImportanceFilter: Create test cases
  src/main/java/athena/Parser.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/task/Task.java
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
  src/test/java/athena/task/taskfilter/ImportanceFilterTest.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: aspect.Testing, priority.High, type.Task

#72 IO redirection test
  .gitignore
  build.gradle
  savedata.csv
  src/main/java/athena/Athena.java
  src/main/java/athena/Parser.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: aspect.Testing, priority.High

#48 create exceptions package
  .gitignore
  save.csv
  src/main/java/athena/Athena.java
  src/main/java/athena/Forecast.java
  src/main/java/athena/Importance.java
  src/main/java/athena/Parser.java
  src/main/java/athena/Recurrence.java
  src/main/java/athena/Storage.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/Ui.java
  src/main/java/athena/commands/AddCommand.java
  src/main/java/athena/commands/Command.java
  src/main/java/athena/commands/DeleteCommand.java
  src/main/java/athena/commands/DoneCommand.java
  src/main/java/athena/commands/EditCommand.java
  src/main/java/athena/commands/ListCommand.java
  src/main/java/athena/exceptions/AddException.java
  src/main/java/athena/exceptions/AddMissingRequiredParametersException.java
  src/main/java/athena/exceptions/CommandException.java
  src/main/java/athena/exceptions/DeleteInvalidIndexException.java
  src/main/java/athena/exceptions/DeleteNoIndexException.java
  src/main/java/athena/exceptions/DoneInvalidIndexException.java
  src/main/java/athena/exceptions/DoneNoIndexException.java
  src/main/java/athena/exceptions/EditNoIndexException.java
  src/main/java/athena/exceptions/EmptyTaskListException.java
  src/main/java/athena/exceptions/InvalidCommandException.java
  src/main/java/athena/exceptions/TaskNotFoundException.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/timetable/Timetable.java
  src/main/java/athena/timetable/TimetableDay.java
  src/test/java/athena/ParserTest.java
  src/test/java/athena/commands/AddCommandTest.java
  src/test/java/athena/commands/DoneCommandTest.java
  src/test/java/athena/taskfilter/ForecastFilterTest.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: aspect.ErrorHandling, priority.High

#80 Create tests for getFilteredList()
  src/main/java/athena/TaskList.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: aspect.Testing, priority.High, severity.VeryLow, type.Task

#87 Fix broken tests
  src/main/java/athena/Parser.java
  src/test/java/athena/taskfilter/ForecastFilterTest.java
Labels: priority.High, severity.High, type.Bug

#92 Badly handle invalid date format for now
  src/main/java/athena/task/Task.java
Labels: aspect.ErrorHandling, priority.High

#99 Generate a date for tests in ForecastFilterTest instead of using a fixed one
  .github/workflows/gradle.yml
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
  src/test/java/athena/tasklist/TaskListTest.java
  text-ui-test/EXPECTED.TXT
Labels: aspect.Testing, priority.High

#112 Temporary fix for week filter tests
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: aspect.Testing, priority.High, severity.High

#97 Update Storage to allow commas in task attributes
  src/main/java/athena/Storage.java
  src/test/java/athena/StorageTest.java
Labels: type.Bug

#115 Allow recurrence
  src/main/java/athena/TaskList.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/Time.java
  src/main/java/athena/task/taskfilter/FlexibleTimeFilter.java
  src/main/java/athena/task/taskfilter/ForecastFilter.java
  src/main/java/athena/task/taskfilter/ImportanceFilter.java
  src/main/java/athena/timetable/Timetable.java
  src/test/java/athena/task/TaskTest.java
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
Labels: aspect.Feature, priority.High, severity.Medium, type.Enhancement

#110 Add view command and shortcut commands
  docs/UserGuide.md
  src/main/java/athena/Parser.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/Ui.java
  src/main/java/athena/commands/ViewCommand.java
  src/main/java/athena/exceptions/ViewInvalidIndexException.java
  src/main/java/athena/exceptions/ViewNoIndexException.java
  src/main/java/athena/task/Task.java
  src/test/java/athena/ParserTest.java
Labels: aspect.UIX, priority.High

#122 103 refactor time
  src/main/java/athena/Parser.java
  src/main/java/athena/Storage.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/Time.java
  src/main/java/athena/timetable/TimetableDay.java
Labels: aspect.CodeQuality, priority.Medium, severity.Low

#116 Draw Timetable
  docs/UserGuide.md
  src/main/java/athena/Parser.java
  src/main/java/athena/Storage.java
  src/main/java/athena/task/Time.java
  src/main/java/athena/timetable/Timetable.java
  src/main/java/athena/timetable/TimetableDay.java
  src/test/java/athena/ParserTest.java
  src/test/java/athena/StorageTest.java
  src/test/java/athena/StorageTestAnswer1.csv
  src/test/java/athena/StorageTestAnswer2.csv
  src/test/java/athena/TestSetup.java
  src/test/java/athena/commands/AddCommandTest.java
  src/test/java/athena/commands/DeleteCommandTest.java
  src/test/java/athena/commands/DoneCommandTest.java
  src/test/java/athena/commands/EditCommandTest.java
  src/test/java/athena/tasklist/TaskListTest.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.UIX, priority.High, type.Task

#136 DeveloperGuide: Add implementation details for allocator and storage
  athena.jar
  docs/DeveloperGuide.md
Labels: aspect.Documentation, priority.High

#130 TaskList Component DG
  docs/DeveloperGuide.md
  docs/structures/TaskListStructure.png
Labels: aspect.Documentation, type.Task

#133 Add one v2 user story
  docs/DeveloperGuide.md
Labels: aspect.Documentation

#135 Add Documentation, Testing, DevOps guides, and instructions to manually test storage
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Testing.md
Labels: aspect.Documentation, priority.High

#146 Resolve clash in start times of tasks in TestSetup
  src/test/java/athena/StorageTestAnswer1.csv
  src/test/java/athena/StorageTestAnswer2.csv
  src/test/java/athena/TestSetup.java
  src/test/java/athena/tasklist/TaskListTest.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.Testing, priority.High, severity.High

#140 ForecastFilterTest: Generate dates for week-related tests
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
Labels: aspect.Testing, priority.High

#141 Timetable: Change to use default locale
  src/main/java/athena/timetable/Timetable.java
Labels: severity.Low

#139 Storage: Don't set max number because it is handled by tasklist
  src/main/java/athena/Storage.java
  src/test/java/athena/StorageMaxNumberTest.csv
  src/test/java/athena/StorageTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#118 Change default switch statement of parse
  src/main/java/athena/logic/Parser.java
  src/test/java/athena/ParserTest.java
Labels: aspect.ErrorHandling

#148 Generate dates for Timetable based on Forecast value
  src/main/java/athena/common/utils/DateUtils.java
  src/main/java/athena/task/taskfilter/ForecastFilter.java
  src/main/java/athena/timetable/Timetable.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.Feature, priority.High

#119 Remove UI calls from Storage
  src/main/java/athena/Athena.java
  src/main/java/athena/Storage.java
  src/main/java/athena/Ui.java
  src/main/java/athena/exceptions/StorageCorruptedException.java
  src/main/java/athena/exceptions/StorageException.java
  src/main/java/athena/exceptions/StorageLoadFailException.java
  src/main/java/athena/logic/Logic.java
  src/main/java/athena/logic/LogicManager.java
  src/test/java/athena/StorageTest.java
Labels: aspect.ErrorHandling, priority.High

#145 Check for overlapping tasks
  src/main/java/athena/Storage.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/Ui.java
  src/main/java/athena/exceptions/ClashInTaskException.java
  src/main/java/athena/logic/commands/AddCommand.java
  src/main/java/athena/logic/commands/EditCommand.java
  src/test/java/athena/StorageMaxNumberTest.csv
  src/test/java/athena/StorageTest.java
  src/test/java/athena/TestSetup.java
  src/test/java/athena/TimeAllocatorTest.java
  src/test/java/athena/logic/commands/AddCommandTest.java
  src/test/java/athena/logic/commands/DeleteCommandTest.java
  src/test/java/athena/logic/commands/DoneCommandTest.java
  src/test/java/athena/logic/commands/EditCommandTest.java
  src/test/java/athena/tasklist/TaskListTest.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.ErrorHandling, priority.Medium

#143 Edit UG, add Ui component to DG
  .gitignore
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/structures/UiStructure.png
  src/main/java/athena/AllocationFailedException.java
  src/main/java/athena/Athena.java
  src/main/java/athena/Storage.java
  src/main/java/athena/exceptions/AddMissingRequiredParametersException.java
  src/main/java/athena/exceptions/ClashInTaskException.java
  src/main/java/athena/exceptions/DeleteInvalidIndexException.java
  src/main/java/athena/exceptions/DeleteNoIndexException.java
  src/main/java/athena/exceptions/DoneInvalidIndexException.java
  src/main/java/athena/exceptions/DoneNoIndexException.java
  src/main/java/athena/exceptions/EditNoIndexException.java
  src/main/java/athena/exceptions/EmptyTaskListException.java
  src/main/java/athena/exceptions/InvalidCommandException.java
  src/main/java/athena/exceptions/StorageCorruptedException.java
  src/main/java/athena/exceptions/StorageLoadFailException.java
  src/main/java/athena/exceptions/TaskNotFoundException.java
  src/main/java/athena/exceptions/ViewInvalidIndexException.java
  src/main/java/athena/exceptions/ViewNoIndexException.java
  src/main/java/athena/logic/LogicManager.java
  src/main/java/athena/logic/commands/AddCommand.java
  src/main/java/athena/logic/commands/Command.java
  src/main/java/athena/logic/commands/DeleteCommand.java
  src/main/java/athena/logic/commands/DoneCommand.java
  src/main/java/athena/logic/commands/EditCommand.java
  src/main/java/athena/logic/commands/ExitCommand.java
  src/main/java/athena/logic/commands/HelpCommand.java
  src/main/java/athena/logic/commands/ListCommand.java
  src/main/java/athena/logic/commands/ViewCommand.java
  src/main/java/athena/ui/AthenaUi.java
  src/main/java/athena/ui/ColorText.java
  src/main/java/athena/ui/Ui.java
  src/test/java/athena/StorageTest.java
  src/test/java/athena/logic/commands/AddCommandTest.java
  src/test/java/athena/logic/commands/DeleteCommandTest.java
  src/test/java/athena/logic/commands/DoneCommandTest.java
  src/test/java/athena/logic/commands/EditCommandTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/runtest.bat
Labels: aspect.Documentation

#161 Some UI improvements
  src/main/java/athena/task/Task.java
  src/main/java/athena/timetable/Timetable.java
  src/main/java/athena/ui/AthenaUi.java
Labels: aspect.UIX

#168 Fix tests again
  src/main/java/athena/common/utils/DateUtils.java
  src/main/java/athena/task/Task.java
  src/test/java/athena/tasklist/TaskListTest.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.Testing, priority.High, severity.High

#176 Check for valid forecast and valid importance
  src/main/java/athena/exceptions/InvalidForecastException.java
  src/main/java/athena/exceptions/InvalidImportanceException.java
  src/main/java/athena/logic/Parser.java
  src/main/java/athena/task/taskfilter/FilterCalculator.java
  src/main/java/athena/ui/AthenaUi.java
Labels: aspect.ErrorHandling

#195 Timetable: Remove dependency on TaskFilter classes
  src/main/java/athena/logic/commands/ListCommand.java
  src/main/java/athena/task/taskfilter/ForecastFilter.java
  src/main/java/athena/timetable/Timetable.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.CodeQuality, priority.Medium
