Repository AY2021S1-CS2113T-W12-2/tp, pull requests merged in 2020-11, with the labels that each got.

#235 UserGuide: Split list command into 3 sections
  docs/UserGuide.md
Labels: aspect.Documentation, priority.High

#233 Solve issue when user input '/' in parameter's description.
  src/main/java/athena/Athena.java
  src/main/java/athena/logic/Parser.java
Labels: aspect.ErrorHandling

#236 Error message when task is already done
  src/main/java/athena/Storage.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/exceptions/TaskIsDoneException.java
  src/main/java/athena/logic/commands/DoneCommand.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/ui/AthenaUi.java
  src/test/java/athena/logic/commands/DoneCommandTest.java
Labels: type.Bug

#243 Change timetable to start from today and print only days with tasks in tasklist
  src/main/java/athena/common/utils/DateUtils.java
  src/main/java/athena/timetable/Timetable.java
Labels: priority.High

#239 Create exceptions for when dates have passed
  src/main/java/athena/Storage.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/TimeAllocator.java
  src/main/java/athena/exceptions/DateHasPassedException.java
  src/main/java/athena/exceptions/InvalidDateFormatException.java
  src/main/java/athena/logic/DateChecker.java
  src/main/java/athena/logic/commands/AddCommand.java
  src/main/java/athena/logic/commands/EditCommand.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/Time.java
  src/main/java/athena/task/taskfilter/ForecastFilter.java
  src/main/java/athena/ui/AthenaUi.java
  src/test/java/athena/ParserTest.java
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: type.Bug

#247 Refactor time allocator
  .gitignore
  src/main/java/athena/Log.java
  src/main/java/athena/TimeAllocator.java
  src/main/java/athena/TimeSlot.java
  src/main/java/athena/exceptions/AllocationFailedException.java
  src/main/java/athena/exceptions/AllocatorException.java
  src/main/java/athena/exceptions/NoNextSlotException.java
  src/test/java/athena/TimeAllocatorTest.java
Labels: type.Enhancement

#262 ForecastFilter: Show tasks happening within one week from today
  src/main/java/athena/task/taskfilter/ForecastFilter.java
Labels: priority.High, type.Bug

#261 Update FAQ and PPP
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/marcus-cheong.jpg
  docs/team/marcus-cheong.md
Labels: PPP

#259 Timetable: Cleanup
  src/main/java/athena/timetable/Timetable.java
  src/main/java/athena/timetable/TimetableDay.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: aspect.CodeQuality

#263 Cleanup TaskFilter classes
  src/main/java/athena/TaskList.java
  src/main/java/athena/TimeAllocator.java
  src/main/java/athena/common/utils/DateUtils.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/taskfilter/DayFilter.java
  src/main/java/athena/task/taskfilter/ForecastFilter.java
  src/main/java/athena/task/taskfilter/ImportanceFilter.java
  src/main/java/athena/timetable/Timetable.java
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
Labels: aspect.CodeQuality

#253 Check for date format of deadline
  src/main/java/athena/Storage.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/TimeAllocator.java
  src/main/java/athena/exceptions/InvalidDateFormatException.java
  src/main/java/athena/exceptions/InvalidDeadlineException.java
  src/main/java/athena/exceptions/InvalidRecurrenceException.java
  src/main/java/athena/logic/DateChecker.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/Time.java
  src/main/java/athena/ui/AthenaUi.java
  src/test/java/athena/ParserTest.java
  src/test/java/athena/StorageMaxNumberTest.csv
  src/test/java/athena/StorageTestAnswer1.csv
  src/test/java/athena/StorageTestAnswer2.csv
  src/test/java/athena/TestSetup.java
  src/test/java/athena/TimeAllocatorTest.java
  src/test/java/athena/logic/commands/AddCommandTest.java
  src/test/java/athena/logic/commands/DeleteCommandTest.java
  src/test/java/athena/logic/commands/DoneCommandTest.java
  src/test/java/athena/logic/commands/EditCommandTest.java
  src/test/java/athena/task/taskfilter/ForecastFilterTest.java
  src/test/java/athena/tasklist/TaskListTest.java
  src/test/java/athena/timetable/TimetableTest.java
Labels: type.Bug

#266 Catch NoSuchLineException by Scanner
  src/main/java/athena/Athena.java
Labels: priority.High, type.Bug

#269 Fix invalid importance crash for add and edit
  src/main/java/athena/logic/Parser.java
  src/main/java/athena/logic/commands/AddCommand.java
  src/test/java/athena/ParserTest.java
  src/test/java/athena/logic/commands/AddCommandTest.java
Labels: priority.High, type.Bug

#280 Add more list tests and refactor timetable methods
  src/main/java/athena/logic/commands/ListCommand.java
  src/main/java/athena/timetable/Timetable.java
  src/main/java/athena/timetable/TimetableDay.java
  src/main/java/athena/timetable/TimetableDrawer.java
  src/test/java/athena/ParserTest.java
  src/test/java/athena/timetable/TimetableDrawerTest.java
  src/test/java/athena/timetable/TimetableTest.java
  src/test/java/athena/timetable/TimetableTestsUtils.java
Labels: aspect.CodeQuality

#283 add table of contents, introduction, quick start, features, help components of UG
  docs/UserGuide.md
  docs/screenshots/help.jpeg
Labels: UG, aspect.Documentation

#278 Add, edit details of UG
  docs/UserGuide.md
  docs/screenshots/add advanced.jpg
  docs/screenshots/add basic.jpg
  docs/screenshots/add intermediate.jpg
  docs/screenshots/edit basic.jpg
  docs/screenshots/edit intermediate.jpg
Labels: UG, aspect.Documentation

#287 UG: Add list and done
  docs/UserGuide.md
  docs/screenshots/add-advanced.jpg
  docs/screenshots/add-basic.jpg
  docs/screenshots/add-intermediate.jpg
  docs/screenshots/dn.jpg
  docs/screenshots/done.jpg
  docs/screenshots/edit-basic.jpg
  docs/screenshots/edit-intermediate.jpg
  docs/screenshots/l2-day.jpg
  docs/screenshots/list-low.jpg
  docs/screenshots/list-week-high.jpg
  docs/screenshots/list.jpg
Labels: UG

#276 Add delete, view, exit details
  docs/UserGuide.md
  docs/screenshots/delete-basic.jpeg
  docs/screenshots/delete-intermediate.jpeg
  docs/screenshots/exit-basic.jpeg
  docs/screenshots/exit-intermediate.jpeg
  docs/screenshots/view-basic.jpeg
  docs/screenshots/view-intermediate.jpeg
Labels: UG, aspect.Documentation

#298 Add exclamation emoji
  docs/UserGuide.md
Labels: UG

#254 Amanda ppp
  docs/AboutUs.md
  docs/team/amanda-chua.md
  docs/team/johndoe.md
  docs/teamPictures/amanda-chua.jpg
Labels: PPP

#277 Task not allocated
  src/main/java/athena/Log.java
  src/main/java/athena/Storage.java
  src/main/java/athena/TaskList.java
  src/main/java/athena/TimeAllocator.java
  src/main/java/athena/exceptions/command/TaskTooLongException.java
  src/main/java/athena/task/Task.java
  src/main/java/athena/task/TimeData.java
  src/main/java/athena/ui/AthenaUi.java
Labels: aspect.ErrorHandling

#288 Delete Developer Guide
  docs/DeveloperGuide.md
Labels: DG

#294 Assign task number if this number is already used by another task
  src/main/java/athena/TaskList.java
  src/test/java/athena/tasklist/TaskListTest.java
Labels: type.Bug

#293 Check if time has passed on same day
  src/main/java/athena/DateChecker.java
  src/main/java/athena/commands/AddCommand.java
  src/main/java/athena/commands/EditCommand.java
  src/main/java/athena/ui/AthenaUi.java
Labels: type.Bug

#313 Allow user to only add hourly tasks
  src/main/java/athena/DateChecker.java
  src/main/java/athena/commands/AddCommand.java
  src/main/java/athena/commands/EditCommand.java
  src/main/java/athena/exceptions/command/TimeNotHourlyException.java
  src/main/java/athena/ui/AthenaUi.java
Labels: aspect.ErrorHandling

#255 add Alston PPP
  docs/AboutUs.md
  docs/team/alstontham.md
  docs/teamPictures/alston-tham.JPG
Labels: PPP

#252 Create PPP for Vish
  docs/AboutUs.md
  docs/team/wish2023.md
  docs/teamPictures/wish2023.png
Labels: PPP

#323 Updated diagrams
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/sequenceDiagrams/AddCommand.png
  docs/sequenceDiagrams/AddCommand.puml
  docs/sequenceDiagrams/DeleteCommand.png
  docs/sequenceDiagrams/DeleteCommand.puml
  docs/sequenceDiagrams/DoneCommand.png
  docs/sequenceDiagrams/DoneCommand.puml
  docs/sequenceDiagrams/EditCommand.png
  docs/sequenceDiagrams/ListCommand.png
  docs/sequenceDiagrams/Parser.png
  docs/sequenceDiagrams/TimeAllocator.png
  docs/sequenceDiagrams/TimeAllocator.puml
  docs/sequenceDiagrams/ViewCommand.png
  docs/sequenceDiagrams/loadStorage.png
  docs/sequenceDiagrams/loadStorage.puml
  docs/sequenceDiagrams/saveStorage.png
  docs/structures/StorageStructure.JPG
  docs/structures/TimeAllocatorStructure.JPG
  docs/team/kafcis.md
  docs/teamPictures/kafcis.jpg
Labels: DG, UG

#325 PPP
  docs/team/kafcis.md
Labels: PPP

#327 Add NFR
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: DG

#328 Update diagrams and links
  docs/DeveloperGuide.md
  docs/UserGuide.html
  docs/sequenceDiagrams/DoneCommand.png
  docs/sequenceDiagrams/ListCommand.png
  docs/structures/ParserStructure.png
  docs/structures/StorageStructure.JPG
  docs/structures/StorageStructure.png
  docs/structures/TimeAllocatorStructure.JPG
  docs/structures/TimeAllocatorStructure.png
Labels: DG

#331 ppap
  docs/AboutUs.md
  docs/DeveloperGuide.html
  docs/team/daniellimws.md
  docs/teamPictures/daniellimws.png
Labels: PPP
